### ISSUE TITLE
Grunt Script to Generate Manifest

### ISSUE THREAD

**Issue by lylepratt** [markmarijnissen/cordova-app-loader#1]
Great project! We were working on our own version (took the redirect to new index.html approach) but are running into issues and want to try yours. One difference is that we were just zipping all of the file contents up into one ZIP file. This prevented us from needed to generate a manifest.

I'm curious if you know of or use a Grunt script to generate your manifest files?

**Comment by rajatrocks** [comment]
The sample Gruntfile expects filenames to be of the format "7230ca97-vendor.js" and then it strips off the first part to create the key "vendor.js". If your filenames don't have a "-" in them, this code returns an empty key ("") and the files object ends up with only the last item in your list because it keeps overwriting the key "".

```javascript
var key = filename.split("-").slice(1).join('-');
```

To get this to work on my code (where there are no dashes in the filenames), I removed the line above and replaced it with: 
```javascript
var key = filename.split("/");
key = key[key.length -1];
```
which sets the key to just the file part of the filename.
