### ISSUE TITLE
App Store updates

### ISSUE THREAD

**Issue by rajatrocks** [markmarijnissen/cordova-app-loader#16]
Hi @markmarijnissen - great library, and I think I have it all working in my app! I was reading through the various closed issues, and I'm still confused on how App Store updates are handled. If I've downloaded the app and then done one or more remote updates, and then download a new version from the App Store, will it copy over the newly downloaded files into the cache, or will it try to do a remote update, or something else? Any insight would be much appreciated. 

best, - rajat

**Comment by markmarijnissen** [comment]
Hi @rajatrocks ,

It's very easy: The Remote Server is your Single Source of Truth.

Also: App-Loader tries to be efficient and minimize downloads:

* Only files whose version has changed are downloaded.
* If the file can be copied from the application bundle (i.e. files in App from App Store), then it will copy instead of download.

How you handle your `check -> update -> download` logic is up to you. 

Let's examine your situation step by step:

1. You download the App. (version 1)
2. You do a remote update (version 2)
3. Your app does a `check -> update -> download`.
4. Your app is version 2.
4. You publish a new version to the App Store (version 3) **and to your remote server**.
5. Before your App can check the remote server, the App is updated from the App Store.
6. Your app still runs version 2 (from the cache) - but it has version 3 files bundled.
7. Your app does a `check -> update -> download`. It detects remote version 3. Instead of downloading the files from Remote, it can copy the files from the Bundle. 
8. Your App is now version 3.
9. You do a remote update (version 4).
10. The app does a   `check -> update -> download`.
11. The update is corrupt, BOOTSTRAP_OK is not fired. App reverts back to bundled version (3).
12. App is now version 3 (running form the bundle instead of cache).
13. The app does a   `check` -- it detects you downloaded this earlier, so it will not update.
14. You do a remote update (version 5) with a bugfix (no more corrupt).
15. The app wil update again.

**Comment by rajatrocks** [comment]
Great explanation, thank you @markmarijnissen !
