### ISSUE TITLE
Using Angular's $q as a Promise library for cordova-promise-fs 

### ISSUE THREAD

**Issue by lylepratt** [markmarijnissen/cordova-app-loader#3]
Hi,

I'm trying to get this to work with Angular's built in Promise functionality, but am having trouble. I don't really understand what i'm supposed to be passing into the cordova-promise-fs init.

```
        // Initialize a FileSystem
        var fs = new CordovaPromiseFS({
          Promise: $q
        });
```

It just says "use your favorite promise library". Its not very clear what exactly will work, or what the cordova-promise-fs is expecting. Is there even a way to get this to work with Angulars promises without having to include an external library?

Many thanks,
Lyle

**Comment by yogibimbi** [comment]
Hi Mark, I found an error in your example code in the Readme.md, that had me stuck when trying to include. You write 

> var fs = CordovaPromiseFS({
>   persistent: true, // or false
>   storageSize: 20*1024*1024, // storage size in bytes, default 20MB 
>   concurrency: 3 // how many concurrent uploads/downloads?
>   Promise: require('promiscuous') // Your favorite Promise/A+ library! 
> });

And I just c&p'd the code and was wondering why replacing "require('promiscuous')" with "$q" resulted in an error. Turns out, there is a comma missing after "concurrency: 3" and Chrome's feedback led me a bit astray before finding that. You might want to correct that;-) Apart from that: congrats and thanks for the library!
