### ISSUE TITLE
how to update image on css?

### ISSUE THREAD

**Issue by jasondu** [markmarijnissen/cordova-app-loader#30]
some image use css loaded,(ex: background-image: url(...)),if we download new image,how to change the url?thanks

**Comment by micky2be** [comment]
+1

**Comment by markmarijnissen** [comment]
* include your stylesheet in the Manifest.json, both in "files" and in "load"

* add all images you use in your CSS to the manifest.json. 


* bootstrap.js will inject your stylesheet using the cache url (after an update)

* use relative urls for images you included in the manifest. Relative paths are resolved against the url of the stylesheet (i.e. In the cache). 






Btw, you should be using relative urls anyway because Cordova launches your app in some arbitrary subdirectory you can't know beforehand (making absolute urls difficult).




Does this answer your question?



—

**Comment by jasondu** [comment]
thank you. this's OK.
