### ISSUE TITLE
problem updating image resources

### ISSUE THREAD

**Issue by doronfeldman** [markmarijnissen/cordova-app-loader#40]
in my manifest.json, i have a .png file that i want to update,
the file path is 'resources/img/image.png'.

somewhere in my html template, i use
\<img src="resources/img/image.png">

when i update the .png file on my server, it is downloaded by the app, 
but the app still loads the original image.

i also noticed in the developer tool that my image is loaded from:
<b>file:///android_asset/www/resources/img/image.png<b>

instead of being loaded from the cache:
cdvfile://localhost/persistent/app/resources/img/image.png (which exists but not used)

by the way, the html template that contins the image tag is part of my .js that is loaded with the bootstrap

is there any way i could solve this?

**Comment by micky2be** [comment]
Sorry I'm a bit late to post an answer but your src is wrong here. It will try to look for the image where the html file is. Which is not in the cache.

You have to put `cdvfile://localhost/persistent/app/resources/img/image.png` directly there instead.

**Comment by zhougn** [comment]
I have a related problem:

I understand that when my App gets updated, I have to put ```cdvfile://localhost/persistent/app/resources/img/image.png``` directly in my html, because the image is downloaded in the cache.

But what if when my App first time runs and there is nothing to update? In this case, all my html and images are still in the bundle folder, not in the cache, there is no such file ```cdvfile://localhost/persistent/app/resources/img/image.png```. Instead ```resources/img/image.png``` is the correct path.

While I don't want to keep two different versions of my html files, is there any solution for the problem?

What I can come up with is to copy all the bundle files to the cache folder when my App first time run, same as @betorobson's thought here: https://github.com/markmarijnissen/cordova-app-loader/issues/50

Is it good idea? And how can I do that?

**Comment by micky2be** [comment]
From what I recall, everything in the bundle is copied to the cache.
So in theory it should work

**Comment by zhougn** [comment]
Just tested on iOS, it doesn't seem to work, and I don't see any related code.
I'm using the latest version of cordova-app-loader.

**Comment by micky2be** [comment]
The code is in there
https://github.com/markmarijnissen/cordova-app-loader/blob/master/www/lib/CordovaAppLoader.js#L211-L217
https://github.com/markmarijnissen/cordova-app-loader/blob/master/www/lib/CordovaAppLoader.js#L274

**Comment by zhougn** [comment]
I think I understand why my App doesn't work in that way, thanks so much.

When there is no file to be deleted or to be downloaded, AppLoader#check method will ```resolve(false)``` according the code:
https://github.com/markmarijnissen/cordova-app-loader/blob/master/www/lib/CordovaAppLoader.js#L236-L246

And I copied a piece of code from
https://github.com/markmarijnissen/cordova-app-loader/blob/master/autoupdate.js#L35-L45

```
  function check(){
    loader.check()
    .then(function(){
      return loader.download();
    })
    .then(function(){
      return loader.update();
    },function(err){
      console.error('Auto-update error:',err);
    });
  }
```

The loader.download() is never called, that's why the bundle files are not copied.

**Comment by ObjectiveTruth** [comment]
@zhougn, I was having the same issue. I resolved it by programmatically adding `cdv://` to each resource I referenced based on whether it was downloaded or not. Its pretty ugly.

Did you find a cleaner solution? I figure having it ALWAYS copy the files to the cache would be best and just append all resources with `cdv://`

**Comment by betorobson** [comment]
It seems to be a long assert, but for me, It looks like that needs just a slight change, before check if has any file changed listed on manifest it could copy all those listed files from bundles to cdvfile:// and them all references to those files can use cdvfile://.

This change could be follow by a kind of parameter or something like that, a optional setting. I don't know actually, it is just a tip but I can be wrong.

**Comment by zhougn** [comment]
I end up with changing ```bootstrap.js``` a little to make sure all bundle files are copied to cache folder on first time run, even when there is no network for the app to check update from remote server. So all the resource references can be prepended with ```cdv://```.

It works for me, but still ugly, and this requires ```cordoba-app-loader-complete.js``` to be loaded before ```bootstrap.js```. It would be great if some simple settings can make things happen.
```
@@ -1,4 +1,38 @@
 (function(){
+
+function copyBundleFiles(manifest) {
+  var isCordova = typeof cordova !== 'undefined';
+
+  var fs = new CordovaPromiseFS({
+    persistent: isCordova, // Chrome should use temporary storage.
+    Promise: Promise
+  });
+
+  var loader = new CordovaAppLoader({
+    fs: fs,
+    localRoot: 'app',
+    serverRoot: './',
+    manifestUrl: 'manifest.json',
+    mode: 'mirror',
+    cacheBuster: true
+  });
+
+  loader.manifest = manifest;
+
+  function downloadBundle() {
+    manifest.root = 'cdvfile://localhost/persistent/app/';
+    loader.newManifest = manifest;
+    return loader.download().then(function() {
+      loader.update();
+      location.reload();
+    });
+  }
+
+  fs.deviceready.then(function(){
+    loader.check(manifest).then(downloadBundle, downloadBundle);
+  });
+}
+
 // Retrieved and slightly modified from: https://github.com/typicode/pegasus
 // --------------------------------------------------------------------------
 //
@@ -68,6 +102,7 @@

 if(!manifest){
   var url = (s? s.getAttribute('manifest'): null) || 'manifest.json';
   // get manifest.json, then loadManifest.
-  pegasus(url).then(loadManifest,function(xhr){
+  pegasus(url).then(copyBundleFiles,function(xhr){
     console.error('Could not download '+url+': '+xhr.status);
```

**Comment by ObjectiveTruth** [comment]
@zhougn , oof that works but I'm worried about the hard coding `cordova-app-loader-complete.js` into the device, incase there's any updates in the future. At least, that's the concern with my use case.

Its an option at least. 

Let me know if you have any ideas for a cleaner solution, hopefully we can build it into the project.

**Comment by betorobson** [comment]
That looks pretty cool. I will try it. Thank you.

**Comment by minhtc** [comment]
@ObjectiveTruth I was having the same issue with you. Could you share your solution here?

**Comment by guv3n** [comment]
@zhougn I tried your piece of code to copy all files to cache to be able to getScripts from cdvfiles://.. but the problem is that after that, the "real" update won't work anymore because files from the update are the same as the one copied in cdvfile (this is made to avoid loop updating if I understand well)
"New manifest available, but an earlier update attempt failed. Will not download."
Did you find a solution to this ?

**Comment by markmarijnissen** [comment]
Use `cache.loader.get` or `manifest.root + originalPath` to find the correct reference to the image source
