### ISSUE TITLE
updating index.html

### ISSUE THREAD

**Issue by qwemaze** [markmarijnissen/cordova-app-loader#49]
Is it possible to update index.html, and how?
Cause after changing several files on a server every one except index.html was updated.

**Comment by micky2be** [comment]
AFAIK you can't.
And I don't think there is a proper strategy to load any other html file (since we talk about a one page app).

That's something we could try to do though. 
Updating the html file can be useful, but my recommendation will be to keep it as simple as possible and to write what you need in JavaScript.

**Comment by ObjectiveTruth** [comment]
Closing since the issues seems to have been answered, please reopen if you still feel there is more to contribute to the conversation :ok_hand:
