### ISSUE TITLE
user closes app during update, on next run check returns false

### ISSUE THREAD

**Issue by chcnetconsulting** [markmarijnissen/cordova-app-loader#65]
Hi all,

I'm facing a really bad problem now on iOS, probably also on Android, which I cannot test right now. 

You can reproduce it like this:

loader.check('http://myserver.com/manifest.json').then(....) tells the user that there is an update waiting, the update starts. the user for what reason ever interrupts the app and swipes it out of memory. At the next run of the app loader.check doesn't detect, that the previous update was interrupted.

check simply does not detect invalid updates. What can I do about this?

Thank you for your help!
Kind regards
Christoph

**Comment by ZackMattor** [comment]
Also would like to know how to handle this...

**Comment by dasilva333** [comment]
I too have this issue, this programming construct while appreciated is meant to prevent the user/client from attempting to endlessly download an invalid update.
This assumes there's something wrong with the code or manifest pushed online and allows the client to resume working with the local copy despite remote issues.
I think this fundamental decision is ultimately up to the programmer to decide, I have an automated work process using Grunt that automatically packs the files
builds the manifest and pushes the files online and I have never in my time using this tool produced a bad manifest that results the need for this check.
Instead the more common situation is the app is loading, whether it's a flaky network, app crash, or the user decides to multi-task during the update it gets interrupted.
At that point we have a valid working online manifest and because the update was interrupted the user is no longer able to get on the latest version.

I came up with a 'fix' workaround which basically just comments/eliminates the interrupted update check and proceeds to download the remote manifest regardless.
You can find the commit for it here:

https://github.com/dasilva333/TowerGhostForDestiny/commit/9a3881d9ef99ebcb86bb6a0ddf0b5e27f59c5e87#diff-524e088d3e590b259e5bcbcad4f5e59eR208

One warning I must add my version of cordova-app-loader complete had also been modified to include Firefox support so only take the diff you see there not the whole file.

Any thoughts @markmarijnissen ?

**Comment by markmarijnissen** [comment]
There is a new option: `preventAutoUpdateLoop` which van be `true` or `false`.

Set to false to disable this check.

Might be good idea to improve the auto update loop check in the future.

**Comment by dasilva333** [comment]
Thanks man! I'll be merging your changes into my code today. That's great stuff.
Here's my diff of your cordova-app-loader complete and mines:

https://github.com/dasilva333/TowerGhostForDestiny/commit/568a65481855f6801af0fc0a15c871af7e942ac1

My changes are only around lines 698-804 where I add support for Firefox's filesystem using this additional plugin:

https://github.com/dasilva333/TowerGhostForDestiny/blob/master/www/js/core/idb.filesystem.js

I also agree with improving the auto update loop a few things that could be improved:

- provide a callback method or event or return a message to the _check _function when this error is thrown:
> New manifest available, but an earlier update attempt failed. Will not download.
- differentiate between an interrupted update and an actual invalid remote manifest
- differentiate between a server timeout and an invalid remote manifest

If these things could be improved I would be willing to eventually go back to preventAutoUpdateLoop: false knowing I can trust once a manifest gets blacklisted.

Thanks for all your hard work!
